// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUordTBD-ZRAo1w0m0BFGWPssgn5-KTwU',
    appId: '1:1087621037558:web:7f9840993bb2c907e29bd7',
    messagingSenderId: '1087621037558',
    projectId: 'flashchat-d77e3',
    authDomain: 'flashchat-d77e3.firebaseapp.com',
    storageBucket: 'flashchat-d77e3.appspot.com',
    measurementId: 'G-54J8B6FJ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpYtc8ZJwlTK_6WI8zyoC3uhvvSA27Zw',
    appId: '1:1087621037558:android:e8d45cb2706c86a1e29bd7',
    messagingSenderId: '1087621037558',
    projectId: 'flashchat-d77e3',
    storageBucket: 'flashchat-d77e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOM9-CSTo4qYFaQ9bBq7H2y-E6KMNR7xk',
    appId: '1:1087621037558:ios:d89f328fec6551b6e29bd7',
    messagingSenderId: '1087621037558',
    projectId: 'flashchat-d77e3',
    storageBucket: 'flashchat-d77e3.appspot.com',
    iosClientId: '1087621037558-8vpdmakqvm90jt7buc02dkkg4fcs7pu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOM9-CSTo4qYFaQ9bBq7H2y-E6KMNR7xk',
    appId: '1:1087621037558:ios:d89f328fec6551b6e29bd7',
    messagingSenderId: '1087621037558',
    projectId: 'flashchat-d77e3',
    storageBucket: 'flashchat-d77e3.appspot.com',
    iosClientId: '1087621037558-8vpdmakqvm90jt7buc02dkkg4fcs7pu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
